# Generated by Django 5.1.2 on 2024-11-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alunos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunosispk',
            old_name='nivel_acade',
            new_name='nivel',
        ),
        migrations.RemoveField(
            model_name='alunosispk',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='alunosispk',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='alunosispk',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='alunosispk',
            name='turma',
        ),
    ]
