# Generated by Django 5.1.2 on 2024-10-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_livros'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunosAspk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateTimeField(blank=True, null=True)),
                ('sala', models.IntegerField()),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('turma', models.CharField(max_length=50)),
                ('nivel_acade', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Alunos',
            },
        ),
    ]
