# Generated by Django 5.1.2 on 2024-11-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alunosaspk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlunosAspk',
        ),
    ]
